spring:
  application:
    name: dbschema
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/dbschema
    username: postgres 
    password: 551551551 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.dbschema.dbschema: DEBUG